### ISSUE TITLE
Heroku demo down

### ISSUE THREAD

**Issue by Gelmo** [cwoolner/flex-poker#1]
It appears that the demo of the app is not working.

**Comment by cwoolner** [comment]
@JoshGelman, thanks for catching this.  It's been working fine locally (using mvn jetty:run), so I never thought to check to see if Heroku was working or not.  Still somewhat confused why I had to add names to some Spring @Component annotations when it works locally without them.  Type erasure should make it fail locally as well as on Heroku, but it does not.  Something to look into later.  Thanks again!

**Comment by Gelmo** [comment]
No problem, glad you found a quick fix!
