### ISSUE TITLE
Email verification not sent in Heroku deployment

### ISSUE THREAD

**Issue by Gelmo** [cwoolner/flex-poker#2]
After creating an account in the demo deployment, no email is sent with activation info.

**Comment by cwoolner** [comment]
Couple of things:
- Wasn't sure if you noticed, but emails not working is mentioned in the "Not done" section of the README
- This isn't super clear in the README, but there are four default logins created, player1/player1, player2/player2, etc.  It's mentioned in the Security section, but it probably needs to be more pronounced.  Anyway, there's no reason to sign yourself up if you just want to use one of those, but you're more than welcome to create your own

All that said, this was worth fixing, at least partially.  The core of how signing up was not changed, but some things on the periphery were adjusted to fake it as if an email was sent.  Adding in real email sending is very low on the priority list.  Fixing this issue also fixed an interesting Spring Security interaction, so I'm happy this got another look.  Sign Up needs tons of love in the styling department, but you should now be able to go through the process.
